/*The fun and easy project “Guess the Number” is a short Java project that allows the user to guess the number generated by the computer & involves the following steps:
The system generates a random number from a given range, say 1 to 100.
The user is prompted to enter their given number in a displayed dialogue box.
The computer then tells if the entered number matches the guessed number, or it is higher/lower than the generated number.
The game continues under the user guessing the number.*/
import java.util.Random;
import java.util.Scanner;

class GuessingGame{
    public int compNumber; //compNumber is the number generated by the Computer that the user has to guess
    public int userGuess; //The number user guesses
    public int noOfGuesses = 0; //Taking a count of the number of times the user takes to guess the correct number

    public int getNoOfGuesses() {
        return noOfGuesses;
    }

    public void setNoOfGuesses(int noOfGuesses) {
        this.noOfGuesses = noOfGuesses;
    }

    GuessingGame(){
        Random rand = new Random();
        this.compNumber = rand.nextInt(100);
    }
    void userInput(){
        System.out.println("Please enter a number: ");
        Scanner sc = new Scanner(System.in);
        userGuess = sc.nextInt();
    }
    boolean correctNumber(){
        noOfGuesses++;
        if (userGuess==compNumber){
            System.out.format("Congratulations! It was a correct guess! The answer is %d\nYou guessed it in %d attempts", compNumber, noOfGuesses);
            return true;
        }
        else if(userGuess<compNumber){
            System.out.println("Oops! Try again with a higher number.");
        }
        else {
            System.out.println("Oops! Try again with a lower number.");
        }
        return false;
    }

}
public class GuessTheNumber {
    public static void main(String[] args) {
        System.out.println("WELCOME TO THE NUMBER GUESSING GAME! Can you think of a number between 0 and 100 that matches with mine?");
        GuessingGame g = new GuessingGame();
        boolean rightGuess= false;
        while(!rightGuess){
            g.userInput();
            rightGuess = g.correctNumber();
        }

    }
}

